### ISSUE TITLE
samtobed.py - unforgiving license terms

### ISSUE THREAD

**Issue by afif-elghraoui** [PacificBiosciences/FALCON_unzip#55]
Is this file (`src/py_utils/samtobed.py`) necessary? A grep through the source code here doesn't indicate that it's used by the package itself. The (lack of) license terms ("All rights reserved") make it illegal to redistribute or do virtually anything else with it without permission. It is probably better to remove it or get a better statement from its author, @arq5x.

**Comment by pb-cdunn** [comment]
Hmmm. That seems to be copied from this thread:
* http://seqanswers.com/forums/showthread.php?t=2446

You're right; the copyright is strict. It was probably an accident, since aquinlan posted that into a public forum, and since it's trivial code. We can write that from scratch easily.

Fortunately, we do not *use* that script in FALCON_unzip. We are only *distributing* it. And Quinlan Lab will not sue anybody over something this small. But I will re-write it and drop the copyright.

**Comment by pb-cdunn** [comment]
It was not even a working script. Deleted completely. Thanks for pointing this out.
